# bot.py
import asyncio
import logging
import os
from pathlib import Path

from telegram import InlineKeyboardButton, InlineKeyboardMarkup, Update
from telegram.ext import ApplicationBuilder, CallbackContext, CommandHandler, CallbackQueryHandler

from config import (
    TELEGRAM_BOT_TOKEN,
    TELEGRAM_CHAT_ID,
    ALPACA_API_KEY,
    ALPACA_API_SECRET,
    ALPACA_BASE_URL,
    MOOMOO_API_KEY,
    MOOMOO_API_SECRET,
    RISK_MAX_EXPOSURE,
    RISK_MAX_TOTAL,
    BROKER,
)

# Backtrader imports
from strategy import HybridStrategy
from data_feeds import AlpacaLiveDataFeed, MoomooLiveDataFeed

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Global async queue for pending orders generated by the strategy
order_queue = asyncio.Queue()

async def start(update: Update, context: CallbackContext):
    await update.message.reply_text("🤖 Bot de trading algorítmico iniciado. Esperando señales…")

async def approve_order(update: Update):
    data = update.callback_query.data
    # Expected format: ACTION|SYMBOL|SIDE|QTY|PRICE
    action, symbol, side, qty, price = data.split("|")
    logger.info(f"Orden aprobada: {side} {qty} {symbol} @ {price}")
    # TODO: aquí llamarías a Alpaca o Moomoo para ejecutar la orden real
    await update.callback_query.answer("✅ Orden ejecutada (simulada)")
    await update.callback_query.edit_message_text(
        f"✅ Orden {side} {qty} {symbol} @ {price} ejecutada (simulada)"
    )

async def cancel_order(update: Update):
    await update.callback_query.answer("❌ Orden cancelada")
    await update.callback_query.edit_message_text("❌ Orden cancelada por el usuario")

async def send_order_confirmation(symbol: str, side: str, qty: int, price: float):
    """Envía al usuario de Telegram una notificación con botones de aprobación.
    side: 'BUY' o 'SELL'
    """
    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    keyboard = [
        [
            InlineKeyboardButton(
                "✅ Ejecutar",
                callback_data=f"APPROVE|{symbol}|{side}|{qty}|{price:.2f}",
            ),
            InlineKeyboardButton(
                "❌ Cancelar",
                callback_data=f"CANCEL|{symbol}|{side}|{qty}|{price:.2f}",
            ),
        ]
    ]
    reply_markup = InlineKeyboardMarkup(keyboard)
    await app.bot.send_message(
        chat_id=TELEGRAM_CHAT_ID,
        text=(
            f"🟢 Señal de trading\n"
            f"Símbolo: {symbol}\n"
            f"Lado: {side}\n"
            f"Cantidad: {qty}\n"
            f"Precio estimado: {price:.2f}\n"
            "¿Ejecutar?"
        ),
        reply_markup=reply_markup,
    )

async def process_orders():
    """Consume orders from the queue and ask for confirmation via Telegram."""
    while True:
        symbol, side, qty, price = await order_queue.get()
        await send_order_confirmation(symbol, side, qty, price)
        order_queue.task_done()

def run_backtrader():
    """Inicializa Backtrader con la estrategia híbrida y el feed en vivo.
    El feed se elige según la variable de entorno ``BROKER`` (alpaca o moomoo).
    """
    import backtrader as bt

    cerebro = bt.Cerebro()
    cerebro.addstrategy(HybridStrategy, order_queue=order_queue)

    if BROKER == "moomoo":
        data = MoomooLiveDataFeed(
            api_key=MOOMOO_API_KEY,
            api_secret=MOOMOO_API_SECRET,
            symbols=["AAPL", "MSFT", "SPY"],
        )
    else:  # default Alpaca
        data = AlpacaLiveDataFeed(
            api_key=ALPACA_API_KEY,
            api_secret=ALPACA_API_SECRET,
            base_url=ALPACA_BASE_URL,
            symbols=["AAPL", "MSFT", "SPY"],
        )
    cerebro.adddata(data)
    cerebro.broker.setcash(100000)  # capital de demo
    cerebro.run()

async def main():
    app = ApplicationBuilder().token(TELEGRAM_BOT_TOKEN).build()
    app.add_handler(CommandHandler("start", start))
    app.add_handler(CallbackQueryHandler(approve_order, pattern="^APPROVE"))
    app.add_handler(CallbackQueryHandler(cancel_order, pattern="^CANCEL"))

    # Ejecutar Backtrader en un thread separado
    loop = asyncio.get_event_loop()
    loop.run_in_executor(None, run_backtrader)

    # Tarea que procesa la cola de órdenes y envía confirmaciones
    asyncio.create_task(process_orders())

    await app.start()
    await app.updater.start_polling()
    logger.info("Bot y motor de trading iniciados")
    await asyncio.Event().wait()

if __name__ == "__main__":
    asyncio.run(main())
